config/routes.rb
Rails.application.routes.draw do
  root 'articles#index', as: 'home'
  resources :articles
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	# Action-Text
	has_rich_text :content
	# Validates
	validates :headline, presence: true
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all.page(params[:page]).per(8)
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		if @article.save
			redirect_to home_path(@article)
		else
			redirect_to home_path
		end
	end

	def destroy
		@article = Article.find(params[:id])
    	@article.destroy
    	if @article.destroy
    	    redirect_to home_path
    	end
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to home_path(@article)
		end
	end

	def show
		@article = Article.find(params[:id])
	end

	private
	def article_params
		params.require(:article).permit(:headline, :content)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <%= form_for @article do |f| %>
        <div class="form-group">
          <%= f.label :headline %>
          <%= f.text_area :headline, class: 'form-control', required: true %>
        </div>
        <div class="form-group">
          <%= f.label :content %>
          <%= f.rich_text_area :content %>
        </div>
        <div class="form-group">
          <br/>
          <%= f.submit class: 'form-control btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <%= link_to "New Post", new_article_path(@article), class: 'btn btn-success me-3' %>
      <% @articles.each do |art| %>
        <div class="alert alert-light">
          <h3>
            <%= art.headline %>
          </h3>
        </div>
        <div class="alert alert-light">
          <p>
            <%= art.content %>
          </p>
          <p>
            <%= art.created_at %>
          </p>
        </div>
        <div class="form-group"></div>
        <br/>
        <div style="display: flex;">
        <%= link_to 'Show', article_path(art), class: 'btn btn-primary me-3' %>
        <%= link_to 'Edit', edit_article_path(art), class: 'btn btn-success me-3' %>
        <%= button_to "Destroy", art, method: :delete, class: 'btn btn-danger' %>
        </div>
        <hr/>
      <% end %>
    </div>
      <ul class="pagination justify-content-center ">
        <li class="page-item">
            <%= paginate @articles %>
        </li>
    </ul>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <%= form_for @article do |f| %>
        <div class="form-group">
          <%= f.label :headline %>
          <%= f.text_area :headline, class: 'form-control', required: true %>
        </div>
        <div class="form-group">
          <%= f.label :content %>
          <%= f.rich_text_area :content, required: true %>
        </div>
        <div class="form-group">
          <br/>
          <%= f.submit class: 'form-control btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1>
        <%= @article.headline %>
      </h1>
      <p>
        <%= @article.content %>
      </p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <br>
    <%= yield %>
  </body>
</html>